services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tetraDX-backend
    ports:
      - "8000:8000"
    volumes:
      - ./staticfiles:/home/app/staticfiles
      - ./media:/home/app/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn _tetradx.wsgi:application -c gunicorn_config.py"
    restart: always
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - DJANGO_LOG_LEVEL=${DJANGO_LOG_LEVEL:-INFO}
      - DB_LOG_LEVEL=${DB_LOG_LEVEL:-WARNING}